#!/bin/bash
# Módulo 06 — Instrucciones de pasos manuales post-bootstrap

LOCAL_IP="$(hostname -I | awk '{print $1}')"

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo -e "${GREEN}${BOLD}  Bootstrap completo.${NC}"
echo ""
echo -e "${YELLOW}${BOLD}  PASOS MANUALES REQUERIDOS${NC}"
echo -e "  (no se pueden automatizar — requieren autenticación interactiva)"
echo ""
echo "  ── 1. SECRETS ─────────────────────────────────────────────"
echo "  Completar los archivos de configuración antes de iniciar"
echo "  los servicios:"
echo ""
echo "    ~/.hermes/.env          → Telegram bot token + OpenCode key"
echo "    ~/.env_agents           → API keys (Anthropic, OpenAI, etc.)"
echo "    $LAB_DIR/repos/paperclip/.env.paperclip"
echo ""
echo "  Templates de referencia en: $SCRIPT_DIR/templates/"
echo "  Generar BETTER_AUTH_SECRET con: openssl rand -hex 32"
echo ""
echo "  ── 2. TAILSCALE ────────────────────────────────────────────"
echo "     sudo tailscale up"
echo ""
echo "  ── 3. GITHUB CLI ───────────────────────────────────────────"
echo "     gh auth login"
echo ""
echo "  ── 4. CLAUDE CODE ──────────────────────────────────────────"
echo "     curl -fsSL https://get.antigravity.dev | bash"
echo "     claude    ← para completar el login"
echo ""
echo "  ── 5. NOTEBOOKLM (nlm) — login headless via CDP ───────────"
echo "     # En el servidor (terminal 1):"
echo "     Xvfb :99 -screen 0 1280x720x24 &"
echo "     export DISPLAY=:99"
echo "     nlm login --force"
echo ""
echo "     # En el servidor (terminal 2):"
echo "     ss -tlnp | grep 9222    ← verificar que Chromium expone CDP"
echo ""
echo "     # Desde tu Mac (terminal local):"
echo "     ssh -L 9222:localhost:9222 $LAB_USER@$LOCAL_IP"
echo ""
echo "     # En Chrome del Mac:"
echo "     Abrir chrome://inspect → Configure → localhost:9222"
echo "     Clic en 'inspect' en el tab de Google Sign-in"
echo "     Completar login de Google normalmente"
echo ""
echo "     # Verificar:"
echo "     nlm notebook list"
echo ""
echo "  ── 6. GEMINI CLI ───────────────────────────────────────────"
echo "     gemini    ← sigue el flujo OAuth en el navegador"
echo ""
echo "  ── 7. OPENCODE ─────────────────────────────────────────────"
echo "     opencode  ← seleccionar provider y autenticar"
echo ""
echo "  ── 8. INICIAR SERVICIOS ────────────────────────────────────"
echo "     # Después de completar los secrets:"
echo "     sudo systemctl start hermes"
echo ""
echo "     # Paperclip:"
echo "     cd $LAB_DIR/repos/paperclip"
echo "     docker compose -f docker/docker-compose.yml \\"
echo "       --env-file .env.paperclip \\"
echo "       --project-name paperclip \\"
echo "       up -d --build"
echo ""
echo "  ── 9. PORTAINER ────────────────────────────────────────────"
echo "     https://$LOCAL_IP:9443    ← crear usuario admin"
echo ""
echo "  Documentación completa: README.md"
echo "═══════════════════════════════════════════════════════════════"
echo ""
