#!/bin/bash
# Módulo 06 — Instrucciones de pasos manuales post-bootstrap

LOCAL_IP="$(hostname -I | awk '{print $1}')"

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo -e "${GREEN}${BOLD}  Bootstrap completo.${NC}"
echo ""
echo -e "${YELLOW}${BOLD}  PASOS MANUALES REQUERIDOS${NC}"
echo -e "  (no se pueden automatizar — requieren autenticación interactiva)"
echo ""
echo "  ── 1. SECRETS ─────────────────────────────────────────────"
echo "  Completar los archivos de configuración antes de iniciar"
echo "  los servicios:"
echo ""
echo "    ~/.hermes/.env          → Telegram bot token + OpenCode key"
echo "    ~/.env_agents           → API keys (Anthropic, OpenAI, etc.)"
echo "    $LAB_DIR/repos/paperclip/.env.paperclip"
echo ""
echo "  Templates de referencia en: $SCRIPT_DIR/templates/"
echo "  Generar BETTER_AUTH_SECRET con: openssl rand -hex 32"
echo ""
echo "  ── 2. TAILSCALE ────────────────────────────────────────────"
echo "     sudo tailscale up"
echo ""
echo "  ── 3. GITHUB CLI ───────────────────────────────────────────"
echo "     gh auth login"
echo ""
echo "  ── 4. CLAUDE CODE ──────────────────────────────────────────"
echo "     claude    ← para completar el login"
echo ""
echo "  ── 5. NOTEBOOKLM (nlm) — login headless via CDP ───────────"
echo "     # En el servidor (terminal 1):"
echo "     Xvfb :99 -screen 0 1280x720x24 &"
echo "     export DISPLAY=:99"
echo "     nlm login --force"
echo ""
echo "     # En el servidor (terminal 2):"
echo "     ss -tlnp | grep 9222    ← verificar que Chromium expone CDP"
echo ""
echo "     # Desde tu Mac (terminal local):"
echo "     ssh -L 9222:localhost:9222 $LAB_USER@$LOCAL_IP"
echo ""
echo "     # En Chrome del Mac:"
echo "     Abrir chrome://inspect → Configure → localhost:9222"
echo "     Clic en 'inspect' en el tab de Google Sign-in"
echo "     Completar login de Google normalmente"
echo ""
echo "     # Verificar:"
echo "     nlm notebook list"
echo ""
echo "  ── 6. ANTIGRAVITY CLI ────────────────────────────────────────"
echo "     antigravity    ← sigue el flujo OAuth en el navegador"
echo ""
echo "  ── 7. OPENCODE ─────────────────────────────────────────────"
echo "     opencode  ← seleccionar provider y autenticar"
echo ""
echo "  ── 8. AGENTES CORE ───────────────────────────────────────────"
echo "     Orden de instalación: Hermes → Paperclip → Odysseus"
echo ""
echo "     # Hermes (agente conversacional Telegram):"
echo "     sudo systemctl start hermes"
echo ""
echo "     # Dagu (systemd user):"
echo "     systemctl --user start dagu"
echo "     # UI: http://<TAILSCALE_IP>:8480 → crear usuario admin"
echo ""
echo "     # MoolMesh (systemd user):"
echo "     systemctl --user start moolmesh"
echo ""
echo "     # Paperclip (desde stacks/, NO desde repos/):"
echo "     cd $LAB_DIR/stacks/paperclip"
echo "     docker compose up -d --build"
echo "     # UI: http://<TAILSCALE_IP>:3100"
echo ""
echo "     # Odysseus:"
echo "     cd $LAB_DIR/stacks/odysseus"
echo "     docker compose up -d --build"
echo ""
echo "  ── 9. INFRA (generados por setup-instance.sh) ─────────────"
echo "     # Levantar stacks de infraestructura:"
echo "     for s in portainer searxng uptime-kuma; do"
echo "       cd $LAB_DIR/stacks/\$s && docker compose up -d"
echo "     done"
echo ""
echo "     # Portainer: https://<TAILSCALE_IP>:9443 → crear admin (5 min)"
echo "     # Uptime Kuma: http://<TAILSCALE_IP>:3001 → crear admin"
echo ""
echo "  ── 10. FILE SHARING ────────────────────────────────────────"
echo ""
echo "     Opción A — Syncthing (sincronización continua):"
echo "       syncthing --device-id"
echo "       # GUI via SSH tunnel: ssh -L 8384:localhost:8384 user@servidor"
echo "       # http://localhost:8384"
echo "       # Desactivar: Global Discovery, Enable Relays, NAT Traversal"
echo "       # Carpeta: knowledge → $LAB_DIR/knowledge"
echo "       # File Versioning: Staggered — 90 días"
echo ""
echo "     Opción B — Tailscale file copy (transferencia puntual):"
echo "       tailscale file cp archivo.md <hostname-destino>:"
echo "       tailscale file get ~/ai-lab/inbox/"
echo ""
echo "  ── 11. SSH — keepalive ─────────────────────────────────────"
echo "     # Servidor: /etc/ssh/sshd_config ya tiene ClientAliveInterval 30"
echo "     # Cliente (tu Mac) — agregar a ~/.ssh/config:"
echo "     #   Host <nombre>"
echo "     #       HostName <ip-tailscale>"
echo "     #       ServerAliveInterval 30"
echo ""
echo "  ── 12. TMUX — sesión persistente del lab ───────────────────"
echo "     lab     ← abre/conecta la sesión tmux del lab"
echo ""
echo "  ── 13. SEARXNG ─────────────────────────────────────────────"
echo "     Agregar a ~/.env_agents:"
echo "       SEARXNG_URL=http://localhost:8080"
echo ""
echo "  Guía completa post-bootstrap: docs/POST-BOOTSTRAP.md"
echo "  (Un agente AI puede leer ese archivo y guiarte paso a paso)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
