# Módulo 03 (Windows host) — Instrucciones de pasos manuales post-bootstrap

Write-Host ""
Write-Host "===================================================================" -ForegroundColor Cyan
Write-Host "  Bootstrap completo (Windows + WSL2)." -ForegroundColor Green
Write-Host ""
Write-Host "  PASOS MANUALES REQUERIDOS" -ForegroundColor Yellow
Write-Host "  (no se pueden automatizar — requieren interacción/GUI)"
Write-Host ""
Write-Host "  -- 1. REINICIO PENDIENTE -----------------------------------------"
Write-Host "     Si el módulo 01 habilitó WSL2 o long paths por primera vez,"
Write-Host "     reiniciar Windows antes de seguir."
Write-Host ""
Write-Host "  -- 2. VERIFICAR DOCKER CE (dentro de WSL2) -----------------------"
Write-Host "     wsl -d Ubuntu -- docker run --rm hello-world"
Write-Host "     wsl -d Ubuntu -- docker compose version"
Write-Host ""
Write-Host "  -- 3. SECRETS (dentro de WSL2) ------------------------------------"
Write-Host "     wsl -d Ubuntu"
Write-Host "     Completar dentro de la distro:"
Write-Host "       ~/ai-lab/scripts/.env"
Write-Host "       ~/.hermes/.env"
Write-Host "       ~/ai-lab/repos/paperclip/.env.paperclip"
Write-Host "     Templates en: ~/ai-lab/repos/ai-lab-bootstrap/templates/"
Write-Host ""
Write-Host "  -- 4. TAILSCALE (en el host Windows) -----------------------------"
Write-Host "     Abrir la app Tailscale desde el menú de inicio y hacer login."
if ($null -eq $isWin11) { $isWin11 = [System.Environment]::OSVersion.Version.Build -ge 22000 }
if ($isWin11) {
  Write-Host "     (WSL2 con networkingMode=mirrored comparte la IP del host)"
} else {
  Write-Host "     NOTA (Windows 10): WSL2 tiene IP propia (NAT). Tailscale del"
  Write-Host "     host NO cubre a WSL2 automaticamente. Si necesitas acceso"
  Write-Host "     Tailscale dentro de WSL2, instalarlo manualmente:"
  Write-Host "       wsl -d Ubuntu -- bash -c 'curl -fsSL https://tailscale.com/install.sh | sh'"
}
Write-Host ""
Write-Host "  -- 5. GITHUB CLI (dentro de WSL2) --------------------------------"
Write-Host "     wsl -d Ubuntu -- gh auth login"
Write-Host ""
Write-Host "  -- 6. CLAUDE CODE (dentro de WSL2) -------------------------------"
Write-Host "     wsl -d Ubuntu"
Write-Host "     claude    <- para completar el login"
Write-Host ""
Write-Host "  -- 7. NOTEBOOKLM (nlm) — login con navegador real ---------------"
Write-Host "     wsl -d Ubuntu -- nlm login --force"
Write-Host ""
Write-Host "  -- 8. INICIAR SERVICIOS (dentro de WSL2) -------------------------"
Write-Host "     wsl -d Ubuntu -- sudo systemctl start hermes"
Write-Host "     wsl -d Ubuntu -- sudo systemctl status hermes"
Write-Host ""
Write-Host "     # Paperclip (Docker CE nativo en WSL2):"
Write-Host "     wsl -d Ubuntu"
Write-Host "     cd ~/ai-lab/repos/paperclip"
Write-Host "     docker compose -f docker/docker-compose.yml \"
Write-Host "       --env-file .env.paperclip --project-name paperclip up -d --build"
Write-Host ""
Write-Host "  -- 9. PORTAINER -------------------------------------------------"
Write-Host "     https://localhost:9443    <- crear usuario admin"
Write-Host ""
Write-Host "  -- 10. SYNCTHING (en el host Windows) ----------------------------"
Write-Host "     Abrir la app Syncthing -> http://localhost:8384"
Write-Host "     Folder Path: \\wsl`$\Ubuntu\home\<user>\ai-lab\knowledge"
Write-Host ""
Write-Host "  -- 11. ARRANQUE AUTOMATICO DE WSL2 AL ENCENDER -------------------"
Write-Host "     WSL2 no arranca solo al boot. Registrar tarea programada:"
Write-Host ""
Write-Host "       `$action = New-ScheduledTaskAction -Execute 'wsl.exe' -Argument '-d Ubuntu -- true'"
Write-Host "       `$trigger = New-ScheduledTaskTrigger -AtLogOn"
Write-Host "       Register-ScheduledTask -TaskName 'WSL2-Ubuntu-Autostart' ``"
Write-Host "         -Action `$action -Trigger `$trigger -RunLevel Highest"
Write-Host ""
Write-Host "  MANTENIMIENTO WSL2:" -ForegroundColor Yellow
Write-Host ""
Write-Host "  - Recuperar espacio disco (el .vhdx crece pero no se achica solo):"
Write-Host "    wsl -d Ubuntu -- sudo fstrim -av"
Write-Host ""
Write-Host "  - Verificar systemd (servicios activos):"
Write-Host "    wsl -d Ubuntu -- systemctl list-units --type=service --state=running"
Write-Host ""
Write-Host "  - Verificar .wslconfig aplicado:"
Write-Host "    wsl --status"
Write-Host ""
Write-Host "  - Si la máquina se suspende (sleep), WSL2 y sus servicios systemd"
Write-Host "    se detienen. No es equivalente a un servidor siempre encendido."
Write-Host ""
Write-Host "  - Docker CE corre dentro de WSL2 (NO Docker Desktop). Los stacks"
Write-Host "    Docker Compose (Paperclip, Glance, etc.) levantan dentro de la"
Write-Host "    distro Ubuntu, idéntico al servidor Linux."
Write-Host ""
Write-Host "  Guia detallada (prerrequisitos, W10 vs W11, troubleshooting):"
Write-Host "    docs/WINDOWS-INSTALL.md"
Write-Host ""
Write-Host "  Pasos post-bootstrap completos (secrets, servicios, fases):"
Write-Host "    docs/POST-BOOTSTRAP.md"
Write-Host "===================================================================" -ForegroundColor Cyan
Write-Host ""
