# Módulo 03 (Windows host) — Instrucciones de pasos manuales post-bootstrap

Write-Host ""
Write-Host "===================================================================" -ForegroundColor Cyan
Write-Host "  Bootstrap completo (Windows + WSL2)." -ForegroundColor Green
Write-Host ""
Write-Host "  PASOS MANUALES REQUERIDOS" -ForegroundColor Yellow
Write-Host "  (no se pueden automatizar — requieren interacción/GUI)"
Write-Host ""
Write-Host "  -- 1. REINICIO PENDIENTE -----------------------------------------"
Write-Host "     Si el módulo 01 habilitó WSL2 o long paths por primera vez,"
Write-Host "     reiniciar Windows antes de seguir."
Write-Host ""
Write-Host "  -- 2. DOCKER DESKTOP — integración con WSL2 -----------------------"
Write-Host "     Abrir Docker Desktop -> Settings -> Resources -> WSL Integration"
Write-Host "     Activar el toggle para la distro 'Ubuntu'."
Write-Host "     Verificar dentro de WSL2: wsl -d Ubuntu -- docker info"
Write-Host ""
Write-Host "  -- 3. SECRETS (dentro de WSL2) --------------------------------------"
Write-Host "     wsl -d Ubuntu"
Write-Host "     Completar dentro de la distro:"
Write-Host "       ~/.hermes/.env"
Write-Host "       ~/.env_agents"
Write-Host "       ~/ai-lab/repos/paperclip/.env.paperclip"
Write-Host "     Templates en: ~/ai-lab/repos/ai-lab-bootstrap/templates/"
Write-Host ""
Write-Host "  -- 4. TAILSCALE (en el host Windows) -------------------------------"
Write-Host "     Abrir la app Tailscale desde el menú de inicio y hacer login."
Write-Host ""
Write-Host "  -- 5. GITHUB CLI (dentro de WSL2) -----------------------------------"
Write-Host "     wsl -d Ubuntu -- gh auth login"
Write-Host ""
Write-Host "  -- 6. CLAUDE CODE (dentro de WSL2) -----------------------------------"
Write-Host "     wsl -d Ubuntu"
Write-Host "     claude    <- para completar el login"
Write-Host ""
Write-Host "  -- 7. NOTEBOOKLM (nlm) — login con navegador real -------------------"
Write-Host "     # WSLg permite GUI real desde WSL2 — no hace falta Xvfb/CDP tunnel"
Write-Host "     wsl -d Ubuntu -- nlm login --force"
Write-Host ""
Write-Host "  -- 8. INICIAR SERVICIOS (dentro de WSL2) -----------------------------"
Write-Host "     wsl -d Ubuntu -- sudo systemctl start hermes"
Write-Host "     wsl -d Ubuntu -- sudo systemctl status hermes"
Write-Host ""
Write-Host "     # Paperclip:"
Write-Host "     wsl -d Ubuntu"
Write-Host "     cd ~/ai-lab/repos/paperclip"
Write-Host "     docker compose -f docker/docker-compose.yml \"
Write-Host "       --env-file .env.paperclip --project-name paperclip up -d --build"
Write-Host ""
Write-Host "  -- 9. PORTAINER ------------------------------------------------------"
Write-Host "     https://localhost:9443    <- crear usuario admin"
Write-Host ""
Write-Host "  -- 10. SYNCTHING (en el host Windows) --------------------------------"
Write-Host "     Abrir la app Syncthing -> http://localhost:8384"
Write-Host "     Folder Path a sincronizar: el equivalente Windows de ~/ai-lab/knowledge"
Write-Host "     dentro de WSL2 (accesible desde Windows en: \\wsl\$\Ubuntu\home\<user>\ai-lab\knowledge)"
Write-Host ""
Write-Host "  -- 11. ARRANQUE AUTOMÁTICO DE WSL2 AL ENCENDER -----------------------"
Write-Host "     WSL2 no arranca solo al boot de Windows. Para que el cron @reboot"
Write-Host "     de Linux (lab-session, watchdog) funcione, registrar una tarea"
Write-Host "     programada que arranque la distro al iniciar sesión:"
Write-Host ""
Write-Host "       `$action = New-ScheduledTaskAction -Execute 'wsl.exe' -Argument '-d Ubuntu -- true'"
Write-Host "       `$trigger = New-ScheduledTaskTrigger -AtLogOn"
Write-Host "       Register-ScheduledTask -TaskName 'WSL2-Ubuntu-Autostart' \"
Write-Host "         -Action `$action -Trigger `$trigger -RunLevel Highest"
Write-Host ""
Write-Host "  NOTA IMPORTANTE:" -ForegroundColor Yellow
Write-Host "  - Si esta máquina se suspende (sleep), WSL2 y sus servicios systemd"
Write-Host "    se detienen — igual que en macOS, no es un equivalente 1:1 a un"
Write-Host "    servidor Linux siempre encendido."
Write-Host "  - Todo el trabajo del lab (Hermes, Paperclip, agentes) vive dentro"
Write-Host "    de WSL2 — el host Windows es solo la capa de Docker Desktop +"
Write-Host "    apps GUI (Tailscale, Syncthing)."
Write-Host ""
Write-Host "  Documentación completa: README.md"
Write-Host "===================================================================" -ForegroundColor Cyan
Write-Host ""
