# Modulo 04 (Windows host) --Instrucciones de pasos manuales post-bootstrap

Write-Host ""
Write-Host "===================================================================" -ForegroundColor Cyan
Write-Host "  Bootstrap completo (Windows + WSL2 + agentes nativos)." -ForegroundColor Green
Write-Host ""
Write-Host "  IMPORTANTE: Dentro de WSL2, ejecutar 'source ~/.bashrc' o abrir" -ForegroundColor Yellow
Write-Host "  una nueva terminal para que claude, node y opencode esten en PATH." -ForegroundColor Yellow
Write-Host ""
Write-Host "  PASOS MANUALES REQUERIDOS" -ForegroundColor Yellow
Write-Host "  (no se pueden automatizar --requieren interaccion/GUI)"
Write-Host ""
Write-Host "  -- 1. REINICIO PENDIENTE -----------------------------------------"
Write-Host "     Si el modulo 01 habilito WSL2 o long paths por primera vez,"
Write-Host "     reiniciar Windows antes de seguir."
Write-Host ""
Write-Host "  -- 2. VERIFICAR DOCKER CE (dentro de WSL2) -----------------------"
Write-Host "     NOTA: Cerrar y reabrir WSL2 primero para que el grupo docker"
Write-Host "     tome efecto (desde PowerShell: wsl --shutdown, luego wsl -d Ubuntu)"
Write-Host "     wsl -d Ubuntu -- docker run --rm hello-world"
Write-Host "     wsl -d Ubuntu -- docker compose version"
Write-Host ""
Write-Host "  -- 3. SECRETS (WSL2 + Windows) -----------------------------------"
Write-Host "     Capa WSL2:"
Write-Host "       wsl -d Ubuntu"
Write-Host "       Completar: ~/ai-lab/scripts/.env"
Write-Host "                   ~/.hermes/.env"
Write-Host "                   ~/ai-lab/repos/paperclip/.env.paperclip"
Write-Host "       Templates en: ~/ai-lab/repos/ai-lab-bootstrap/templates/"
Write-Host ""
Write-Host "     Capa nativa Windows:"
Write-Host "       %USERPROFILE%\.hermes\.env     (Telegram token, user IDs)"
Write-Host "       %USERPROFILE%\.env_agents      (API keys para agentes)"
Write-Host ""
Write-Host "  -- 4. HERMES GATEWAY SETUP (nativo) -----------------------------"
Write-Host "     cd %USERPROFILE%\ai-lab\repos\hermes-agent"
Write-Host "     uv run hermes gateway setup"
Write-Host "     (completa: Telegram bot token, allowed user IDs, etc.)"
Write-Host ""
Write-Host "  -- 5. INICIAR SERVICIOS NATIVOS ----------------------------------"
Write-Host "     servy start HermesGateway"
Write-Host "     servy start HermesDashboard"
Write-Host "     servy start MoolMesh"
Write-Host ""
Write-Host "     Verificar:"
Write-Host "       http://localhost:9119  (Hermes Dashboard)"
Write-Host "       http://localhost:5200  (MoolMesh)"
Write-Host ""
Write-Host "  -- 6. TAILSCALE (en el host Windows) -----------------------------"
Write-Host "     Abrir la app Tailscale desde el menu de inicio y hacer login."
if ($null -eq $isWin11) { $isWin11 = [System.Environment]::OSVersion.Version.Build -ge 22000 }
if ($isWin11) {
  Write-Host "     (WSL2 con networkingMode=mirrored comparte la IP del host)"
} else {
  Write-Host "     NOTA (Windows 10): WSL2 tiene IP propia (NAT). Tailscale del"
  Write-Host "     host NO cubre a WSL2 automaticamente. Si necesitas acceso"
  Write-Host "     Tailscale dentro de WSL2, instalarlo manualmente:"
  Write-Host "       wsl -d Ubuntu -- bash -c 'curl -fsSL https://tailscale.com/install.sh | sh'"
}
Write-Host ""
Write-Host "  -- 7. GITHUB CLI (dentro de WSL2) --------------------------------"
Write-Host "     wsl -d Ubuntu -- gh auth login"
Write-Host "     NOTA: WSL2 no puede abrir el browser automaticamente."
Write-Host "     Seleccionar 'Login with a web browser', copiar el codigo,"
Write-Host "     y abrir la URL en el browser de Windows manualmente."
Write-Host "     O seleccionar 'Paste an authentication token' con un PAT"
Write-Host "     de github.com/settings/tokens"
Write-Host ""
Write-Host "  -- 8. CLAUDE CODE LOGIN -----------------------------------------"
Write-Host "     Nativo (Windows): claude"
Write-Host "     WSL2:             wsl -d Ubuntu -- claude"
Write-Host ""
Write-Host "  -- 9. NOTEBOOKLM (nlm) --login con navegador real ---------------"
Write-Host "     nlm login --force"
Write-Host "     (usa el Chromium del host --no necesita WSL2)"
Write-Host ""
Write-Host "  -- 10. CONFIGURAR MCP SERVERS ------------------------------------"
Write-Host "     En Claude Code y OpenCode nativos, configurar:"
Write-Host "       MoolMesh:      localhost:5200 (nativo)"
Write-Host "       Engram:        stdio (binario local)"
Write-Host "       Playwright:    stdio (npm global, headed)"
Write-Host "       NotebookLM:    stdio (uv tool)"
Write-Host "       Paperclip:     localhost:3100 (WSL2 via portproxy)"
Write-Host "       Dagu:          localhost:8084 (WSL2 via portproxy)"
Write-Host ""
Write-Host "  -- 11. INICIAR SERVICIOS WSL2 ------------------------------------"
Write-Host "     wsl -d Ubuntu -- sudo systemctl start hermes"
Write-Host "     wsl -d Ubuntu -- sudo systemctl status hermes"
Write-Host ""
Write-Host "     # Paperclip (Docker CE nativo en WSL2):"
Write-Host "     wsl -d Ubuntu"
Write-Host "     cd ~/ai-lab/repos/paperclip"
Write-Host "     docker compose -f docker/docker-compose.yml \"
Write-Host "       --env-file .env.paperclip --project-name paperclip up -d --build"
Write-Host ""
Write-Host "  -- 12. PORT FORWARDING WSL2 --------------------------------------"
Write-Host "     Ejecutar manualmente la primera vez (luego corre al logon):"
Write-Host "     powershell -ExecutionPolicy Bypass -File %USERPROFILE%\ai-lab\scripts\update-portproxy.ps1"
Write-Host ""
Write-Host "  -- 13. PORTAINER ------------------------------------------------"
Write-Host "     https://localhost:9443    <- crear usuario admin"
Write-Host ""
Write-Host "  -- 14. SYNCTHING (en el host Windows) ----------------------------"
Write-Host "     Abrir la app Syncthing -> http://localhost:8384"
Write-Host "     Folder Path: \\wsl`$\Ubuntu\home\<user>\ai-lab\knowledge"
Write-Host ""
Write-Host "  -- 15. ARRANQUE AUTOMATICO DE WSL2 AL ENCENDER -------------------"
Write-Host "     WSL2 no arranca solo al boot. Registrar tarea programada:"
Write-Host ""
Write-Host "       `$action = New-ScheduledTaskAction -Execute 'wsl.exe' -Argument '-d Ubuntu -- true'"
Write-Host "       `$trigger = New-ScheduledTaskTrigger -AtLogOn"
Write-Host "       Register-ScheduledTask -TaskName 'WSL2-Ubuntu-Autostart' ``"
Write-Host "         -Action `$action -Trigger `$trigger -RunLevel Highest"
Write-Host ""
Write-Host "  MANTENIMIENTO:" -ForegroundColor Yellow
Write-Host ""
Write-Host "  - Servicios nativos: servy list / servy status <nombre>"
Write-Host "  - Logs Servy: servy logs <nombre>"
Write-Host "  - Recuperar espacio disco WSL2:"
Write-Host "    wsl -d Ubuntu -- sudo fstrim -av"
Write-Host "  - Verificar systemd WSL2:"
Write-Host "    wsl -d Ubuntu -- systemctl list-units --type=service --state=running"
Write-Host "  - Verificar .wslconfig:"
Write-Host "    wsl --status"
Write-Host "  - Si la maquina se suspende (sleep), WSL2 y servicios systemd"
Write-Host "    se detienen. Servy re-inicia los servicios nativos al boot."
Write-Host ""
Write-Host "  Guia detallada (prerrequisitos, W10 vs W11, troubleshooting):"
Write-Host "    docs/WINDOWS-INSTALL.md"
Write-Host ""
Write-Host "  Pasos post-bootstrap completos (secrets, servicios, fases):"
Write-Host "    docs/POST-BOOTSTRAP.md"
Write-Host "===================================================================" -ForegroundColor Cyan
Write-Host ""
