# Modulo 06 -- Pasos manuales post-bootstrap

Write-Host ""
Write-Host "===================================================================" -ForegroundColor Cyan
Write-Host "  Bootstrap completo (Windows nativo)." -ForegroundColor Green
Write-Host ""
Write-Host "  PASOS MANUALES REQUERIDOS" -ForegroundColor Yellow
Write-Host "  (no se pueden automatizar --requieren interaccion)"
Write-Host ""
Write-Host "  -- 1. TAILSCALE -------------------------------------------------"
Write-Host "     Abrir Tailscale desde el menu de inicio y hacer login."
Write-Host "     Verificar: tailscale status"
Write-Host ""
Write-Host "  -- 2. SECRETS ----------------------------------------------------"
Write-Host "     Completar los archivos de secrets creados:"
Write-Host "       %USERPROFILE%\.hermes\.env      (Telegram token, user IDs)"
Write-Host "       %USERPROFILE%\.env_agents       (API keys, SearXNG URL)"
Write-Host ""
Write-Host "  -- 3. HERMES GATEWAY SETUP ---------------------------------------"
Write-Host "     cd %USERPROFILE%\ai-lab\repos\hermes-agent"
Write-Host "     uv run hermes gateway setup"
Write-Host "     (configura: Telegram bot, allowed users, modelo default)"
Write-Host ""
Write-Host "  -- 4. INICIAR SERVICIOS ------------------------------------------"
Write-Host "     servy start HermesGateway"
Write-Host "     servy start HermesDashboard"
Write-Host "     servy start MoolMesh"
Write-Host "     servy start UptimeKuma"
Write-Host "     servy start Glance"
Write-Host "     servy start Paperclip"
Write-Host "     servy start Odysseus"
Write-Host ""
Write-Host "     Verificar: servy list"
Write-Host ""
Write-Host "  -- 5. HEALTH CHECKS ---------------------------------------------"
Write-Host "     curl http://localhost:9119/api/health    (Hermes)"
Write-Host "     curl http://localhost:5200/api/sessions  (MoolMesh)"
Write-Host "     curl http://localhost:8480               (Dagu)"
Write-Host "     curl http://localhost:3001               (Uptime Kuma)"
Write-Host "     curl http://localhost:5678               (Glance)"
Write-Host "     curl http://localhost:3100               (Paperclip)"
Write-Host "     curl http://localhost:7000               (Odysseus)"
Write-Host ""
Write-Host "  -- 6. LOGINS DE AGENTES -----------------------------------------"
Write-Host "     claude           <- completar login interactivo"
Write-Host "     nlm login        <- NotebookLM (abre Chromium)"
Write-Host "     gh auth login    <- GitHub CLI"
Write-Host ""
Write-Host "  -- 7. CONFIGURAR MCP SERVERS ------------------------------------"
Write-Host "     En Claude Code y OpenCode, configurar MCP:"
Write-Host "       MoolMesh:      localhost:5200"
Write-Host "       Engram:        stdio (binario local)"
Write-Host "       Playwright:    stdio (@playwright/mcp, headed)"
Write-Host "       NotebookLM:    stdio (nlm)"
Write-Host "       Paperclip:     localhost:3100"
Write-Host ""
Write-Host "  -- 8. DAGU ADMIN ------------------------------------------------"
Write-Host "     Abrir http://localhost:8480"
Write-Host "     Crear usuario admin si es primera vez."
Write-Host ""
Write-Host "  -- 9. UPTIME KUMA -----------------------------------------------"
Write-Host "     Abrir http://localhost:3001"
Write-Host "     Crear usuario admin, configurar monitors."
Write-Host ""
Write-Host "  MANTENIMIENTO:" -ForegroundColor Yellow
Write-Host ""
Write-Host "  - Ver servicios:     servy list"
Write-Host "  - Logs de servicio:  servy logs <nombre>"
Write-Host "  - Reiniciar:         servy restart <nombre>"
Write-Host "  - Detener:           servy stop <nombre>"
Write-Host ""
Write-Host "  - SearXNG es REMOTO (no soportado nativo Windows)."
Write-Host "    Configurar SEARXNG_URL en ~/.env_agents apuntando a una instancia."
Write-Host ""
Write-Host "  Guia detallada: docs/WINDOWS-INSTALL.md"
Write-Host "===================================================================" -ForegroundColor Cyan
Write-Host ""
