#!/bin/bash
# Módulo 06 (macOS) — Instrucciones de pasos manuales post-bootstrap

LOCAL_IP="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo "<tu-ip-local>")"

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo -e "${GREEN}${BOLD}  Bootstrap completo (macOS).${NC}"
echo ""
echo -e "${YELLOW}${BOLD}  PASOS MANUALES REQUERIDOS${NC}"
echo -e "  (no se pueden automatizar — requieren autenticación interactiva)"
echo ""
echo "  ── 1. SECRETS ─────────────────────────────────────────────"
echo "  Completar los archivos de configuración antes de iniciar"
echo "  los servicios:"
echo ""
echo "    ~/.hermes/.env          → Telegram bot token + OpenCode key"
echo "    ~/.env_agents           → API keys (Anthropic, OpenAI, etc.)"
echo "    $LAB_DIR/repos/paperclip/.env.paperclip"
echo ""
echo "  Templates de referencia en: $SCRIPT_DIR/templates/"
echo "  Generar BETTER_AUTH_SECRET con: openssl rand -hex 32"
echo ""
echo "  ── 2. DOCKER DESKTOP ────────────────────────────────────────"
echo "     Verificar que está corriendo: docker info"
echo "     Si no abrió solo: open -a Docker"
echo ""
echo "  ── 3. TAILSCALE ────────────────────────────────────────────"
echo "     Abrir la app Tailscale desde Launchpad y hacer login,"
echo "     o: tailscale up"
echo ""
echo "  ── 4. GITHUB CLI ───────────────────────────────────────────"
echo "     gh auth login"
echo ""
echo "  ── 5. CLAUDE CODE ──────────────────────────────────────────"
echo "     claude    ← para completar el login"
echo ""
echo "  ── 6. NOTEBOOKLM (nlm) — login con navegador real ─────────"
echo "     # En Mac NO se necesita Xvfb ni túnel CDP — hay pantalla."
echo "     nlm login --force"
echo "     # Se abre Chromium normal, completar login de Google."
echo ""
echo "     # Verificar:"
echo "     nlm notebook list"
echo ""
echo "  ── 7. GEMINI CLI ───────────────────────────────────────────"
echo "     gemini    ← sigue el flujo OAuth en el navegador"
echo ""
echo "  ── 8. OPENCODE ─────────────────────────────────────────────"
echo "     opencode  ← seleccionar provider y autenticar"
echo ""
echo "  ── 9. INICIAR SERVICIOS ────────────────────────────────────"
echo "     # Después de completar los secrets:"
echo "     launchctl load ~/Library/LaunchAgents/com.almacreativa.hermes.plist"
echo "     # Para reiniciar tras cambios:"
echo "     launchctl unload ~/Library/LaunchAgents/com.almacreativa.hermes.plist"
echo "     launchctl load ~/Library/LaunchAgents/com.almacreativa.hermes.plist"
echo "     # Logs:"
echo "     tail -f $LAB_DIR/logs/hermes.log"
echo ""
echo "     # Paperclip:"
echo "     cd $LAB_DIR/repos/paperclip"
echo "     docker compose -f docker/docker-compose.yml \\"
echo "       --env-file .env.paperclip \\"
echo "       --project-name paperclip \\"
echo "       up -d --build"
echo ""
echo "  ── 10. PORTAINER ───────────────────────────────────────────"
echo "     https://localhost:9443    ← crear usuario admin"
echo ""
echo "  ── 11. SYNCTHING — configurar sincronización con Tailscale ───"
echo "     # La GUI escucha solo en localhost:8384 (default — no cambiar)."
echo "     # Acceder en tu propio Mac: http://localhost:8384"
echo ""
echo "     # En GUI → Actions → Settings → GUI:"
echo "     Configurar usuario y contraseña"
echo ""
echo "     # En GUI → Settings → Connections:"
echo "     Listen Addresses: default   ← NO fijar a una IP específica"
echo "     Desactivar: Global Discovery, Enable Relays, NAT Traversal"
echo ""
echo "     # Agregar carpeta sincronizada:"
echo "     Folder ID: knowledge"
echo "     Folder Path: $LAB_DIR/knowledge"
echo "     File Versioning: Staggered — mantener 90 días (protección ransomware)"
echo ""
echo "     # Intercambiar Device IDs con el servidor Linux existente"
echo "     # para sincronizar la misma carpeta knowledge/."
echo ""
echo "  ── 12. SSH — keepalive (si usas este Mac como destino remoto) ──"
echo "     # System Settings → General → Sharing → Remote Login: ON"
echo "     # /etc/ssh/sshd_config ya tiene ClientAliveInterval 30 (aplicado por este bootstrap)"
echo ""
echo "  ── 13. TMUX — sesión persistente del lab ───────────────────"
echo "     # Macs portátiles no quedan encendidos 24/7 — el cron @reboot"
echo "     # solo dispara si el Mac realmente reinicia, no al despertar de sleep."
echo "     # Para abrir la sesión manualmente:"
echo "     lab"
echo ""
echo "  ── 14. SEARXNG — activar en Hermes ──────────────────────────"
echo "     Agregar a ~/.env_agents:"
echo "     SEARXNG_URL=http://localhost:8080"
echo ""
echo "     Verificar que Hermes lo detecta:"
echo "     hermes   →   /tools  →  buscar 'web_search backend'"
echo ""
echo -e "  ${YELLOW}NOTA IMPORTANTE — DIFERENCIAS VS. LINUX:${NC}"
echo "  • Si este Mac es un laptop, el lab NO corre 24/7 salvo que esté"
echo "    siempre encendido y conectado — considera dejarlo como entorno"
echo "    de desarrollo/testing, no como servidor productivo."
echo "  • Docker Desktop consume más RAM en reposo que Docker CE en Linux."
echo "  • launchd reinicia el LaunchAgent de Hermes solo mientras haya"
echo "    sesión de usuario activa (no antes del login)."
echo ""
echo "  Documentación completa: README.md"
echo "═══════════════════════════════════════════════════════════════"
echo ""
