#!/bin/bash
# Módulo 06 (macOS) — Instrucciones de pasos manuales post-bootstrap

LOCAL_IP="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo "<tu-ip-local>")"

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo -e "${GREEN}${BOLD}  Bootstrap completo (macOS).${NC}"
echo ""
echo -e "${YELLOW}${BOLD}  PASOS MANUALES REQUERIDOS${NC}"
echo -e "  (no se pueden automatizar — requieren autenticación interactiva)"
echo ""
echo "  ── 1. SECRETS ─────────────────────────────────────────────"
echo "  Completar los archivos de configuración antes de iniciar"
echo "  los servicios:"
echo ""
echo "    ~/.hermes/.env          → Telegram bot token + OpenCode key"
echo "    ~/.env_agents           → API keys (Anthropic, OpenAI, etc.)"
echo "    $LAB_DIR/repos/paperclip/.env.paperclip"
echo ""
echo "  Templates de referencia en: $SCRIPT_DIR/templates/"
echo "  Generar BETTER_AUTH_SECRET con: openssl rand -hex 32"
echo ""
echo "  ── 2. POSTGRESQL ──────────────────────────────────────────"
echo "     # Verificar que está corriendo:"
echo "     brew services list | grep postgresql"
echo ""
echo "     # Conectarse a la DB de Paperclip:"
echo "     psql -U paperclip -d paperclip"
echo ""
echo "     # Backup manual:"
echo "     pg_dump -U paperclip paperclip > ~/ai-lab/backups/paperclip-\$(date +%F).sql"
echo ""
echo "  ── 3. TAILSCALE ────────────────────────────────────────────"
echo "     Abrir la app Tailscale desde Launchpad y hacer login,"
echo "     o: tailscale up"
echo ""
echo "  ── 4. GITHUB CLI ───────────────────────────────────────────"
echo "     gh auth login"
echo ""
echo "  ── 5. CLAUDE CODE ──────────────────────────────────────────"
echo "     claude    ← para completar el login"
echo ""
echo "  ── 6. NOTEBOOKLM (nlm) — login con navegador real ─────────"
echo "     nlm login --force"
echo "     nlm notebook list"
echo ""
echo "  ── 7. GEMINI CLI ───────────────────────────────────────────"
echo "     gemini    ← sigue el flujo OAuth en el navegador"
echo ""
echo "  ── 8. OPENCODE ─────────────────────────────────────────────"
echo "     opencode  ← seleccionar provider y autenticar"
echo ""
echo "  ── 9. INICIAR SERVICIOS ────────────────────────────────────"
echo "     # PostgreSQL (ya corriendo via brew services):"
echo "     brew services list | grep postgresql"
echo ""
echo "     # Hermes:"
echo "     launchctl load ~/Library/LaunchAgents/com.almacreativa.hermes.plist"
echo "     tail -f $LAB_DIR/logs/hermes.log"
echo ""
echo "     # Paperclip (nativo — sin Docker):"
echo "     launchctl load ~/Library/LaunchAgents/com.almacreativa.paperclip.plist"
echo "     tail -f $LAB_DIR/logs/paperclip.log"
echo "     # UI: http://localhost:3100"
echo ""
echo "     # Dagu (orquestador de workflows):"
echo "     launchctl load ~/Library/LaunchAgents/com.almacreativa.dagu.plist"
echo "     # UI: http://localhost:8480"
echo ""
echo "     # Para reiniciar cualquier servicio:"
echo "     launchctl kickstart -k gui/\$(id -u)/com.almacreativa.<servicio>"
echo ""
echo "  ── 10. SEARXNG — remoto via Tailscale ──────────────────────"
echo "     # En macOS, SearXNG no se instala localmente."
echo "     # Se usa el SearXNG del servidor Linux via Tailscale."
echo "     Agregar a ~/.env_agents:"
echo "     SEARXNG_URL=http://100.79.30.67:8080"
echo ""
echo "     Verificar que Hermes lo detecta:"
echo "     hermes   →   /tools  →  buscar 'web_search backend'"
echo ""
echo "  ── 11. SYNCTHING — configurar sincronización con Tailscale ───"
echo "     http://localhost:8384"
echo ""
echo "     En GUI → Settings → Connections:"
echo "     Desactivar: Global Discovery, Enable Relays, NAT Traversal"
echo ""
echo "     Agregar carpeta sincronizada:"
echo "     Folder ID: knowledge"
echo "     Folder Path: $LAB_DIR/knowledge"
echo "     File Versioning: Staggered — mantener 90 días"
echo ""
echo "     Intercambiar Device IDs con el servidor Linux."
echo ""
echo "  ── 12. SSH — keepalive ─────────────────────────────────────"
echo "     /etc/ssh/sshd_config ya tiene ClientAliveInterval 30"
echo "     (aplicado por este bootstrap)"
echo ""
echo "  ── 13. TMUX — sesión persistente del lab ───────────────────"
echo "     lab     ← abre/conecta la sesión tmux del lab"
echo ""
echo "  ── 14. DAGU — credenciales ─────────────────────────────────"
echo "     # Configurar usuario/contraseña en:"
echo "     ~/.config/dagu/config.yaml → sección auth:"
echo "     # Crear DAGs personalizados para las empresas:"
echo "     ls ~/.config/dagu/dags/*.template"
echo ""
echo -e "  ${YELLOW}NOTA IMPORTANTE — DIFERENCIAS VS. LINUX:${NC}"
echo "  • En macOS todo corre nativo (brew PostgreSQL, Node.js Paperclip,"
echo "    Go Dagu). No se usa Docker."
echo "  • En Linux (servidor i7) Paperclip y Postgres corren en Docker."
echo "  • Los scripts son cross-platform (detectan uname y usan psql"
echo "    directo en Mac o docker exec en Linux)."
echo "  • Si este Mac es un laptop, el lab NO corre 24/7 — considerar"
echo "    como entorno de desarrollo/testing, no servidor productivo."
echo "  • launchd reinicia los LaunchAgents solo mientras haya"
echo "    sesión de usuario activa (no antes del login)."
echo ""
echo "  Documentación completa: README.md"
echo "═══════════════════════════════════════════════════════════════"
echo ""
